apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.6
    imagePullPolicy: IfNotPresent
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: root_passwd
          name: mysql-secret
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          key: user
          name: mysql-secret
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: user_passwd
          name: mysql-secret
    - name: MYSQL_DATABASE
      valueFrom:
        configMapKeyRef:
          key: db_name
          name: mysql-configmap
    ports:
    - containerPort: 3306
      name: mysql
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
